global:
  imageRegistry: ""
  namespaceOverride: ""

image:
  repository: "k8s-ultimate-toolbox"
  tag: "v1.2.0"
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "3Gi"
