global:
  imageRegistry: "myregistry.local:5000"
  namespaceOverride: ""

image:
  repository: "platform/k8s-ultimate-toolbox"
  tag: "v1.2.0"
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: regcred

serviceAccount:
  create: true
  name: ""
  annotations: {}

resources:
  requests:
    cpu: "100m"
    memory: "512Mi"
  limits:
    cpu: "2"
    memory: "3Gi"

customCA:
  enabled: false
  secretName: "toolbox-ca-certs"
  mountPath: /etc/ssl/custom-ca

nodeSelector: {}
tolerations: []
